swagger:
  servers:
    domain:
      local: "http://localhost:8080"
      prd: "https://api-coffee.com"

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/coffee_backend?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: mariadb

  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

jwt:
  issuer: coffee
  secret: coffee-secret
  access:
    timeout-of-minutes: 5
  refresh:
    timeout-of-minutes: 525600

